CREATE TABLE  "USUARIO" (
  "EMAIL" VARCHAR2(255) NOT NULL,
	"RUN" NUMBER(7) NOT NULL UNIQUE,
	"PASSWORD" VARCHAR2(31) NOT NULL,
	"NOMBRE" VARCHAR2(127) NOT NULL,
	"ROL" NUMBER(8) UNIQUE,
	"ESTILO" NUMBER(1),
)
ALTER TABLE "USUARIO"
  ADD PRIMARY KEY ("EMAIL");


CREATE TABLE "CONTENIDOS" (
  "ID" NUMBER(10) NOT NULL,
  "RELEVANCIA_TIPOA" NUMBER(2),



)
